#!/usr/bin/env bash
# sync-platforms.sh
# Generates platform-specific files from the primary source: commands/
# AGENTS.md (root) is hand-curated and NOT regenerated by this script.

set -e

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "Syncing iterative-dev-workflow to platform formats..."

# --- .opencode/commands/ ---
OPENCODE_CMD="$ROOT/.opencode/commands"
mkdir -p "$OPENCODE_CMD"
cp "$ROOT/commands/"*.md "$OPENCODE_CMD/"
echo "  -> .opencode/commands/ synced (${OPENCODE_CMD})"

# --- .agent/workflows/ (Antigravity workflows, singular path) ---
# Same format as commands/*.md (frontmatter + body). Copied verbatim — no transform.
AGENT_WF="$ROOT/.agent/workflows"
mkdir -p "$AGENT_WF"
cp "$ROOT/commands/"*.md "$AGENT_WF/"
echo "  -> .agent/workflows/ synced (${AGENT_WF})"

# --- .agents/skills/workflow-methodology/SKILL.md ---
AGENTS_SKILL="$ROOT/.agents/skills/workflow-methodology"
mkdir -p "$AGENTS_SKILL"
cp "$ROOT/skills/workflow-methodology/SKILL.md" "$AGENTS_SKILL/"
echo "  -> .agents/skills/workflow-methodology/SKILL.md synced"

# NOTE: AGENTS.md (root) is hand-curated for the OpenCode system prompt.
# It is intentionally NOT regenerated from SKILL.md here — the two files
# serve different purposes (system-prompt injection vs. consumer-facing
# plugin payload) and must evolve independently.

# --- Drift check: every commands/*.md must exist in every sync target. ---
missing=0
for f in "$ROOT/commands/"*.md; do
  base=$(basename "$f")
  [ -f "$ROOT/.opencode/commands/$base" ] || { echo "MISSING: .opencode/commands/$base"; missing=1; }
  [ -f "$ROOT/.agent/workflows/$base" ]    || { echo "MISSING: .agent/workflows/$base";    missing=1; }
done
[ "$missing" = 1 ] && { echo "Sync drift detected."; exit 1; }

echo "Done."
